Repository alkemyTech/OT139-SERVER, pull requests merged in 2022-03, with the labels that each got.

#17 OT139-59 Crear migración y modelo de Actividades
  migrations/20220303184251-create-activities.js
  models/activities.js
Labels: enhancement

#13 Ot 139 44 endpoint de eliminar usuario
  constants/httpCodes.js
  controllers/usersController.js
  models/user.js
  package-lock.json
  routes/users.js
Labels: enhancement

#25 Ot-139-71-Create BD Contacts and migration
  migrations/20220304230600-create-contacts.js
  models/contacts.js
Labels: enhancement

#27 Issues update userController and httpCodes
  constants/httpCodes.js
  controllers/usersController.js
Labels: bug

#29 Create migration to rename deleteAt field on entries table
  migrations/20220308002237-rename-column-deleteAt-to-deletedAt-in-entries.js
  models/entries.js
Labels: bug

#24 OT139-32-Endpoint-registro de usuarios
  .env.example
  app.js
  controllers/usersController.js
  migrations/20220302154814-create-user.js
  models/users.js
  package-lock.json
  package.json
  routes/index.js
  routes/users.js
  seeders/20201109013159-create-demo-user.js
Labels: enhancement

#20 Ot 139 52 Añadir middleware de validacion de usuario administrador
  constants/user.js
  middlewares/verify.js
Labels: enhancement, validation

#36 OT139-63 Endpoint Eliminar Novedades
  controllers/newsController.js
  controllers/newsControllers.js
  models/entries.js
  routes/news.js
Labels: enhancement

#18 OT139-36 Endpoint datos usuario autenticado
  app.js
  controllers/authController.js
  controllers/usersController.js
  helpers/jwt.js
  middleware/authMiddleware.js
  routes/auth.js
Labels: enhancement

#34 OT139-45-SERVER-Endpoint-lista-new-create
  controllers/newsController.js
  package-lock.json
  package.json
  routes/news.js
Labels: enhancement

#52 OT139-78 Agregar campos de contacto a organizations
  migrations/20220315173058-add-social-media-fields-to-organization.js
  seeders/20220315175304-add-social-media-to-organization.js
Labels: enhancement

#61 OT139-89 Endpoint para listar Miembros
  controllers/membersController.js
  routes/members.js
Labels: enhancement

#47 OT-139-86-Endpoint-eliminacion-de-testimonios
  controllers/testimonialsController.js
  package.json
  routes/testimonials.js
Labels: enhancement

#39 OT-139-96-Endpoint-Listado-de-Categorias
  app.js
  controllers/categoriesController.js
  package-lock.json
  routes/categories.js
Labels: enhancement

#84 Se arreglaron varios errores en el endpoint /contacts
  constants/user.js
  controllers/contactController.js
  middlewares/verify.js
Labels: bug
